### PR TITLE
Release v1.0.3

### PR DESCRIPTION
**Pull request by ganemone**

### CODE REVIEW

**Comment by mlmorg** [comment]
A couple of questions:
- Can we link to the browser-tests buildkite job to make sure this works across all plugins?
- Did you see #96 is also in this release? Is that ok?
- We should discuss rollout strategy

**Comment by ganemone** [comment]
> Can we link to the browser-tests buildkite job to make sure this works across all plugins?

Afaik this job is running on an interval as of now, not on every release. We need to do some work to speed it up probably before we can run it on every release. To somewhat address your concern, I did publish a prerelease of this package (and all the others that I am going through releasing right now) and I tested it locally and in production with a real application. Obviously that doesn't scale forever though.

> Did you see #96 is also in this release? Is that ok?

Yea that is fine - we need to roll that out.

> We should discuss rollout strategy

Definitely we need to make some improvements here. I think the biggest next step is going to be working on speeding up the release verification build that kevin has worked on and then running that automatically on every release PR.

**Comment by ganemone** [comment]
!merge

**Comment by mlmorg** [comment]
Yes, we should run a build manually on every release until the process is automated.

**Pull request merged**
